
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: proxy
  labels:
    id: "C0916667"
    app: wordpress
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: proxy-config
