apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secrets
    namespace: wordpress
data:
    #ENC[AES256_GCM,data:sYerRgwkK8hQUWyqxJdYPPz3JyPVtGtoSEYu,iv:8sDfiXgQdrSHE1cc6BSOe8W49tN4ojsaCqGuX35eCck=,tag:pzMQmKicz72yO8XGhUkVSA==,type:comment]
    WORDPRESS_DB_USER: ENC[AES256_GCM,data:b9nFzE4tXQUFQbxX,iv:7pKBLbaiLdvJuxqKZiWxGnnYTWIB21uJ6lEkRKPgbUk=,tag:LLljWAJoXoRyU27o+iEbjg==,type:str]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:RebVt6eKfwNN9v+M,iv:FnrgaW694DsSqpAcHHE6Y0MibMaDeBi6L6uv7so68N0=,tag:Vuvbuanhj9kX9pnpXNU+DA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/inlaid-tribute-434723-u5/locations/northamerica-northeast1/keyRings/my-key/cryptoKeys/my-key
          created_at: "2024-11-16T23:26:33Z"
          enc: CiQAwvrWNu3E7khSNekM8HrDdjEVsJEgxSn2Q2tSShbUXOesUxYSSADJpFWulh+vYgUlEEEGST06rmHbQNjST3swTgCE1NJ6ULmgZCV6F2L3hFP3STuYt2fHq5LD/VgfghVoPWPZWianZ8i/X5LZTw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-16T23:26:33Z"
    mac: ENC[AES256_GCM,data:Tk8ovZUki0FLL2/v5ZIFnAv2TneL22vVCoTv1OdoaCt4a0Q3dBzRTYBXAbb10y7TaeW34dlMsTGmUySWNpfDTdEI7g20uMcaiTKI7t02xPHQCg6cMfwdbUw6antrG5XvDqSvZS9Dt7+Cs1Ns8WhMjhngCHqIz6tk6hNsHMK8SnU=,iv:qW8TByWx9pB66arl8Ir+Z0wPiJ0H3R+KyF0zdbWwDOY=,tag:QHFuhfLnx6iGBZSJ+fV5/w==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
