apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress
data:
  WORDPRESS_DB_HOST: mariadb-service.database.svc.cluster.local
  WORDPRESS_DB_NAME: wordpress
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: database
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: proxy
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://35.237.53.55:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Host $host;
      }
    }


